export const enum VALIDATION_CODE {
  PASS = 'PASS',
  EMPTY_EMAIL = 'EMPTY_EMAIL',
  EMPTY_PASSWORD = 'EMPTY_PASSWORD',
  EMPTY_PASSWORD_CONFIRM = 'EMPTY_PASSWORD_CONFIRM',
  PATTERN_ERROR_EMAIL = 'PATTERN_ERROR_EMAIL',
  PATTERN_ERROR_PASSWORD = 'PATTERN_ERROR_PASSWORD',
  PATTERN_ERROR_PASSWORD_CONFIRM = 'PATTERN_ERROR_PASSWORD_CONFIRM',
  CHECK_EMAIL = 'CHECK_EMAIL',
  CHECK_PASSWORD = 'CHECK_PASSWORD',
}

export const VALIDATION_MESSAGE = {
  [VALIDATION_CODE.PASS]: '',
  [VALIDATION_CODE.EMPTY_EMAIL]: '이메일을 입력해 주세요.',
  [VALIDATION_CODE.EMPTY_PASSWORD]: '비밀번호를 입력해 주세요.',
  [VALIDATION_CODE.EMPTY_PASSWORD_CONFIRM]: '비밀번호를 입력해 주세요.',
  [VALIDATION_CODE.PATTERN_ERROR_EMAIL]: '올바른 이메일 주소가 아닙니다.',
  [VALIDATION_CODE.PATTERN_ERROR_PASSWORD]:
    '비밀번호는 영문, 숫자 조합 8자 이상 입력해 주세요.',
  [VALIDATION_CODE.PATTERN_ERROR_PASSWORD_CONFIRM]:
    '비밀번호가 일치하지 않아요.',
  [VALIDATION_CODE.CHECK_EMAIL]: '이메일을 확인해 주세요.',
  [VALIDATION_CODE.CHECK_PASSWORD]: '비밀번호를 확인해 주세요.',
};
